import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import './globals.css';
import NavBar from './nav/NavBar';
import SignalRProvider from './providers/SignalRProvider';
import ToasterProvider from './providers/ToasterProvider';

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <SessionProvider>
          <ToasterProvider />
          <NavBar />
          <main className='container mx-auto px-5 pt-10'>
            <SignalRProvider>{children}</SignalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
